---
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 6
  sourceType: 'module'
  ecmaFeatures:
    jsx: true
env:
  browser: true
  es6: true
  node: true
  jest: true
globals:
  expect: true
  __DEV__: true
plugins:
  - '@typescript-eslint'
  - prettier
  - react
  - react-hooks
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
rules:
  react/state-in-constructor: off
  react/destructuring-assignment: off
  import/no-cycle: off
  react/forbid-prop-types: off
  react/jsx-filename-extension: off
