repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.44.0' # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        files: \.jsx?$ # *.js, *.jsx
        types: [file]

