trailingComma: 'all'
tabWidth: 2
bracketSpacing: true
singleQuote: true
printWidth: 85
arrowParens: 'avoid'
stripNewlines: true
importTypeOrder: ['NPMPackages', 'localImportsValue', 'localImportsType']
plugins: ['prettier-plugin-tailwindcss', 'prettier-plugin-sort-imports']
