export const schemaTablesNonSystemMock = ['new_schema'];

export const schemaTableColumnMock = {
  cols: [
    'table_schema',
    'table_name',
    'column_name',
    'quoted_table_schema',
    'quoted_table_name',
    'quoted_column_name',
    'data_type',
  ],
  col_types: [4, 4, 4, 4, 4, 4, 4],
  rows: [
    [
      'gc',
      'alembic_version',
      'version_num',
      'gc',
      'alembic_version',
      'version_num',
      'text',
    ],
    ['gc', 'jwt_refresh_token', 'id', 'gc', 'jwt_refresh_token', 'id', 'text'],
    [
      'information_schema',
      'character_sets',
      'character_repertoire',
      'information_schema',
      'character_sets',
      'character_repertoire',
      'text',
    ],
    [
      'information_schema',
      'character_sets',
      'character_set_catalog',
      'information_schema',
      'character_sets',
      'character_set_catalog',
      'text',
    ],
    ['new_schema', 'new_table', 'id', 'new_schema', 'new_table', 'id', 'bigint'],
    [
      'pg_catalog',
      'pg_am',
      'amhandler',
      'pg_catalog',
      'pg_am',
      'amhandler',
      'regproc',
    ],
    ['pg_catalog', 'pg_am', 'amname', 'pg_catalog', 'pg_am', 'amname', 'text'],
    [
      'sys',
      'allocations',
      'current_state',
      'sys',
      'allocations',
      'current_state',
      'text',
    ],
    [
      'sys',
      'allocations',
      'decisions',
      'sys',
      'allocations',
      'decisions',
      'object_array',
    ],
    [
      'sys',
      'allocations',
      "decisions['explanations']",
      'sys',
      'allocations',
      "decisions['explanations']",
      'text_array_array',
    ],
  ],
  rowcount: 10,
  duration: 2.215816,
};
