export const schameTablesNonSystemMock = ['new_schema'];

export const schemaTableColumnMock = {
  cols: ['table_schema', 'table_name', 'column_name', 'data_type'],
  col_types: [4, 4, 4, 4],
  rows: [
    ['gc', 'alembic_version', 'version_num', 'text'],
    ['gc', 'jwt_refresh_token', 'id', 'text'],
    ['gc', 'jwt_refresh_token', 'refresh_token', 'text'],
    ['gc', 'scheduled_jobs', 'id', 'text'],
    ['gc', 'scheduled_jobs', 'dc', 'object'],
    ['gc', 'scheduled_jobs', "dc['modified']", 'bigint'],
    ['gc', 'scheduled_jobs', "dc['created']", 'bigint'],
    ['gc', 'scheduled_jobs', 'name', 'text'],
    ['gc', 'scheduled_jobs', 'cron', 'text'],
    ['gc', 'scheduled_jobs', 'enabled', 'boolean'],
    ['gc', 'scheduled_jobs', 'sql', 'text'],
    ['gc', 'scheduled_jobs', 'sql_queries', 'text_array'],
    ['gc', 'scheduled_jobs', 'task', 'object'],
    ['gc', 'scheduled_jobs', "task['type']", 'text'],
    ['gc', 'scheduled_jobs', "task['parameters']", 'object'],
    ['gc', 'scheduled_jobs_log', 'job_id', 'text'],
    ['gc', 'scheduled_jobs_log', 'start', 'timestamp with time zone'],
    ['gc', 'scheduled_jobs_log', 'month', 'timestamp with time zone'],
    ['gc', 'scheduled_jobs_log', 'end', 'timestamp with time zone'],
    ['gc', 'scheduled_jobs_log', 'error', 'text'],
    ['gc', 'scheduled_jobs_log', 'statements', 'object'],
    ['gc', 'scheduled_jobs_state', 'id', 'text'],
    ['gc', 'scheduled_jobs_state', 'next_run_time', 'double precision'],
    ['gc', 'scheduled_jobs_state', 'job_state', 'text'],
    ['information_schema', 'character_sets', 'character_repertoire', 'text'],
    ['information_schema', 'character_sets', 'character_set_catalog', 'text'],
    ['information_schema', 'character_sets', 'character_set_name', 'text'],
    ['information_schema', 'character_sets', 'character_set_schema', 'text'],
    ['information_schema', 'character_sets', 'default_collate_catalog', 'text'],
    ['information_schema', 'character_sets', 'default_collate_name', 'text'],
    ['information_schema', 'character_sets', 'default_collate_schema', 'text'],
    ['information_schema', 'character_sets', 'form_of_use', 'text'],
    ['information_schema', 'columns', 'character_maximum_length', 'integer'],
    ['information_schema', 'columns', 'character_octet_length', 'integer'],
    ['information_schema', 'columns', 'character_set_catalog', 'text'],
    ['information_schema', 'columns', 'character_set_name', 'text'],
    ['information_schema', 'columns', 'character_set_schema', 'text'],
    ['information_schema', 'columns', 'check_action', 'integer'],
    ['information_schema', 'columns', 'check_references', 'text'],
    ['information_schema', 'columns', 'collation_catalog', 'text'],
    ['information_schema', 'columns', 'collation_name', 'text'],
    ['information_schema', 'columns', 'collation_schema', 'text'],
    ['information_schema', 'columns', 'column_default', 'text'],
    ['information_schema', 'columns', 'column_details', 'object'],
    ['information_schema', 'columns', "column_details['name']", 'text'],
    ['information_schema', 'columns', "column_details['path']", 'text_array'],
    ['information_schema', 'columns', 'column_name', 'text'],
    ['information_schema', 'columns', 'data_type', 'text'],
    ['information_schema', 'columns', 'datetime_precision', 'integer'],
    ['information_schema', 'columns', 'domain_catalog', 'text'],
    ['information_schema', 'columns', 'domain_name', 'text'],
    ['information_schema', 'columns', 'domain_schema', 'text'],
    ['information_schema', 'columns', 'generation_expression', 'text'],
    ['information_schema', 'columns', 'identity_cycle', 'boolean'],
    ['information_schema', 'columns', 'identity_generation', 'text'],
    ['information_schema', 'columns', 'identity_increment', 'text'],
    ['information_schema', 'columns', 'identity_maximum', 'text'],
    ['information_schema', 'columns', 'identity_minimum', 'text'],
    ['information_schema', 'columns', 'identity_start', 'text'],
    ['information_schema', 'columns', 'interval_precision', 'integer'],
    ['information_schema', 'columns', 'interval_type', 'text'],
    ['information_schema', 'columns', 'is_generated', 'text'],
    ['information_schema', 'columns', 'is_identity', 'boolean'],
    ['information_schema', 'columns', 'is_nullable', 'boolean'],
    ['information_schema', 'columns', 'numeric_precision', 'integer'],
    ['information_schema', 'columns', 'numeric_precision_radix', 'integer'],
    ['information_schema', 'columns', 'numeric_scale', 'integer'],
    ['information_schema', 'columns', 'ordinal_position', 'integer'],
    ['information_schema', 'columns', 'table_catalog', 'text'],
    ['information_schema', 'columns', 'table_name', 'text'],
    ['information_schema', 'columns', 'table_schema', 'text'],
    ['information_schema', 'columns', 'udt_catalog', 'text'],
    ['information_schema', 'columns', 'udt_name', 'text'],
    ['information_schema', 'columns', 'udt_schema', 'text'],
    [
      'information_schema',
      'foreign_server_options',
      'foreign_server_catalog',
      'text',
    ],
    ['information_schema', 'foreign_server_options', 'foreign_server_name', 'text'],
    ['information_schema', 'foreign_server_options', 'option_name', 'text'],
    ['information_schema', 'foreign_server_options', 'option_value', 'text'],
    ['information_schema', 'foreign_servers', 'authorization_identifier', 'text'],
    [
      'information_schema',
      'foreign_servers',
      'foreign_data_wrapper_catalog',
      'text',
    ],
    ['information_schema', 'foreign_servers', 'foreign_data_wrapper_name', 'text'],
    ['information_schema', 'foreign_servers', 'foreign_server_catalog', 'text'],
    ['information_schema', 'foreign_servers', 'foreign_server_name', 'text'],
    ['information_schema', 'foreign_servers', 'foreign_server_type', 'text'],
    ['information_schema', 'foreign_servers', 'foreign_server_version', 'text'],
    ['information_schema', 'foreign_table_options', 'foreign_table_catalog', 'text'],
    ['information_schema', 'foreign_table_options', 'foreign_table_name', 'text'],
    ['information_schema', 'foreign_table_options', 'foreign_table_schema', 'text'],
    ['information_schema', 'foreign_table_options', 'option_name', 'text'],
    ['information_schema', 'foreign_table_options', 'option_value', 'text'],
    ['information_schema', 'foreign_tables', 'foreign_server_catalog', 'text'],
    ['information_schema', 'foreign_tables', 'foreign_server_name', 'text'],
    ['information_schema', 'foreign_tables', 'foreign_table_catalog', 'text'],
    ['information_schema', 'foreign_tables', 'foreign_table_name', 'text'],
    ['information_schema', 'foreign_tables', 'foreign_table_schema', 'text'],
    ['information_schema', 'key_column_usage', 'column_name', 'text'],
    ['information_schema', 'key_column_usage', 'constraint_catalog', 'text'],
    ['information_schema', 'key_column_usage', 'constraint_name', 'text'],
    ['information_schema', 'key_column_usage', 'constraint_schema', 'text'],
    ['information_schema', 'key_column_usage', 'ordinal_position', 'integer'],
    ['information_schema', 'key_column_usage', 'table_catalog', 'text'],
    ['information_schema', 'key_column_usage', 'table_name', 'text'],
    ['information_schema', 'key_column_usage', 'table_schema', 'text'],
    ['information_schema', 'referential_constraints', 'constraint_catalog', 'text'],
    ['information_schema', 'referential_constraints', 'constraint_name', 'text'],
    ['information_schema', 'referential_constraints', 'constraint_schema', 'text'],
    ['information_schema', 'referential_constraints', 'delete_rule', 'text'],
    ['information_schema', 'referential_constraints', 'match_option', 'text'],
    [
      'information_schema',
      'referential_constraints',
      'unique_constraint_catalog',
      'text',
    ],
    [
      'information_schema',
      'referential_constraints',
      'unique_constraint_name',
      'text',
    ],
    [
      'information_schema',
      'referential_constraints',
      'unique_constraint_schema',
      'text',
    ],
    ['information_schema', 'referential_constraints', 'update_rule', 'text'],
    ['information_schema', 'routines', 'data_type', 'text'],
    ['information_schema', 'routines', 'is_deterministic', 'boolean'],
    ['information_schema', 'routines', 'routine_body', 'text'],
    ['information_schema', 'routines', 'routine_definition', 'text'],
    ['information_schema', 'routines', 'routine_name', 'text'],
    ['information_schema', 'routines', 'routine_schema', 'text'],
    ['information_schema', 'routines', 'routine_type', 'text'],
    ['information_schema', 'routines', 'specific_name', 'text'],
    ['information_schema', 'schemata', 'schema_name', 'text'],
    ['information_schema', 'sql_features', 'comments', 'text'],
    ['information_schema', 'sql_features', 'feature_id', 'text'],
    ['information_schema', 'sql_features', 'feature_name', 'text'],
    ['information_schema', 'sql_features', 'is_supported', 'boolean'],
    ['information_schema', 'sql_features', 'is_verified_by', 'text'],
    ['information_schema', 'sql_features', 'sub_feature_id', 'text'],
    ['information_schema', 'sql_features', 'sub_feature_name', 'text'],
    ['information_schema', 'table_constraints', 'constraint_catalog', 'text'],
    ['information_schema', 'table_constraints', 'constraint_name', 'text'],
    ['information_schema', 'table_constraints', 'constraint_schema', 'text'],
    ['information_schema', 'table_constraints', 'constraint_type', 'text'],
    ['information_schema', 'table_constraints', 'initially_deferred', 'text'],
    ['information_schema', 'table_constraints', 'is_deferrable', 'text'],
    ['information_schema', 'table_constraints', 'table_catalog', 'text'],
    ['information_schema', 'table_constraints', 'table_name', 'text'],
    ['information_schema', 'table_constraints', 'table_schema', 'text'],
    ['information_schema', 'table_partitions', 'closed', 'boolean'],
    ['information_schema', 'table_partitions', 'number_of_replicas', 'text'],
    ['information_schema', 'table_partitions', 'number_of_shards', 'integer'],
    ['information_schema', 'table_partitions', 'partition_ident', 'text'],
    ['information_schema', 'table_partitions', 'routing_hash_function', 'text'],
    ['information_schema', 'table_partitions', 'settings', 'object'],
    ['information_schema', 'table_partitions', "settings['blocks']", 'object'],
    [
      'information_schema',
      'table_partitions',
      "settings['blocks']['metadata']",
      'boolean',
    ],
    [
      'information_schema',
      'table_partitions',
      "settings['blocks']['read']",
      'boolean',
    ],
    [
      'information_schema',
      'table_partitions',
      "settings['blocks']['read_only']",
      'boolean',
    ],
    [
      'information_schema',
      'table_partitions',
      "settings['blocks']['read_only_allow_delete']",
      'boolean',
    ],
    [
      'information_schema',
      'table_partitions',
      "settings['blocks']['write']",
      'boolean',
    ],
    ['information_schema', 'table_partitions', "settings['codec']", 'text'],
    ['information_schema', 'table_partitions', "settings['mapping']", 'object'],
    [
      'information_schema',
      'table_partitions',
      "settings['mapping']['total_fields']",
      'object',
    ],
    [
      'information_schema',
      'table_partitions',
      "settings['mapping']['total_fields']['limit']",
      'integer',
    ],
    ['information_schema', 'table_partitions', "settings['merge']", 'object'],
    [
      'information_schema',
      'table_partitions',
      "settings['merge']['scheduler']",
      'object',
    ],
    [
      'information_schema',
      'table_partitions',
      "settings['merge']['scheduler']['max_merge_count']",
      'integer',
    ],
    [
      'information_schema',
      'table_partitions',
      "settings['merge']['scheduler']['max_thread_count']",
      'integer',
    ],
    ['information_schema', 'table_partitions', "settings['routing']", 'object'],
    [
      'information_schema',
      'table_partitions',
      "settings['routing']['allocation']",
      'object',
    ],
    [
      'information_schema',
      'table_partitions',
      "settings['routing']['allocation']['enable']",
      'text',
    ],
    [
      'information_schema',
      'table_partitions',
      "settings['routing']['allocation']['exclude']",
      'object',
    ],
    [
      'information_schema',
      'table_partitions',
      "settings['routing']['allocation']['include']",
      'object',
    ],
    [
      'information_schema',
      'table_partitions',
      "settings['routing']['allocation']['require']",
      'object',
    ],
    [
      'information_schema',
      'table_partitions',
      "settings['routing']['allocation']['total_shards_per_node']",
      'integer',
    ],
    ['information_schema', 'table_partitions', "settings['store']", 'object'],
    ['information_schema', 'table_partitions', "settings['store']['type']", 'text'],
    ['information_schema', 'table_partitions', "settings['translog']", 'object'],
    [
      'information_schema',
      'table_partitions',
      "settings['translog']['durability']",
      'text',
    ],
    [
      'information_schema',
      'table_partitions',
      "settings['translog']['flush_threshold_size']",
      'bigint',
    ],
    [
      'information_schema',
      'table_partitions',
      "settings['translog']['sync_interval']",
      'bigint',
    ],
    ['information_schema', 'table_partitions', "settings['unassigned']", 'object'],
    [
      'information_schema',
      'table_partitions',
      "settings['unassigned']['node_left']",
      'object',
    ],
    [
      'information_schema',
      'table_partitions',
      "settings['unassigned']['node_left']['delayed_timeout']",
      'bigint',
    ],
    ['information_schema', 'table_partitions', "settings['warmer']", 'object'],
    [
      'information_schema',
      'table_partitions',
      "settings['warmer']['enabled']",
      'boolean',
    ],
    ['information_schema', 'table_partitions', "settings['write']", 'object'],
    [
      'information_schema',
      'table_partitions',
      "settings['write']['wait_for_active_shards']",
      'text',
    ],
    ['information_schema', 'table_partitions', 'table_name', 'text'],
    ['information_schema', 'table_partitions', 'table_schema', 'text'],
    ['information_schema', 'table_partitions', 'values', 'object'],
    ['information_schema', 'table_partitions', 'version', 'object'],
    ['information_schema', 'table_partitions', "version['created']", 'text'],
    ['information_schema', 'table_partitions', "version['upgraded']", 'text'],
    ['information_schema', 'tables', 'blobs_path', 'text'],
    ['information_schema', 'tables', 'closed', 'boolean'],
    ['information_schema', 'tables', 'clustered_by', 'text'],
    ['information_schema', 'tables', 'column_policy', 'text'],
    ['information_schema', 'tables', 'number_of_replicas', 'text'],
    ['information_schema', 'tables', 'number_of_shards', 'integer'],
    ['information_schema', 'tables', 'partitioned_by', 'text_array'],
    ['information_schema', 'tables', 'reference_generation', 'text'],
    ['information_schema', 'tables', 'routing_hash_function', 'text'],
    ['information_schema', 'tables', 'self_referencing_column_name', 'text'],
    ['information_schema', 'tables', 'settings', 'object'],
    ['information_schema', 'tables', "settings['blocks']", 'object'],
    ['information_schema', 'tables', "settings['blocks']['metadata']", 'boolean'],
    ['information_schema', 'tables', "settings['blocks']['read']", 'boolean'],
    ['information_schema', 'tables', "settings['blocks']['read_only']", 'boolean'],
    [
      'information_schema',
      'tables',
      "settings['blocks']['read_only_allow_delete']",
      'boolean',
    ],
    ['information_schema', 'tables', "settings['blocks']['write']", 'boolean'],
    ['information_schema', 'tables', "settings['codec']", 'text'],
    ['information_schema', 'tables', "settings['mapping']", 'object'],
    [
      'information_schema',
      'tables',
      "settings['mapping']['total_fields']",
      'object',
    ],
    [
      'information_schema',
      'tables',
      "settings['mapping']['total_fields']['limit']",
      'integer',
    ],
    ['information_schema', 'tables', "settings['merge']", 'object'],
    ['information_schema', 'tables', "settings['merge']['scheduler']", 'object'],
    [
      'information_schema',
      'tables',
      "settings['merge']['scheduler']['max_merge_count']",
      'integer',
    ],
    [
      'information_schema',
      'tables',
      "settings['merge']['scheduler']['max_thread_count']",
      'integer',
    ],
    ['information_schema', 'tables', "settings['refresh_interval']", 'bigint'],
    ['information_schema', 'tables', "settings['routing']", 'object'],
    ['information_schema', 'tables', "settings['routing']['allocation']", 'object'],
    [
      'information_schema',
      'tables',
      "settings['routing']['allocation']['enable']",
      'text',
    ],
    [
      'information_schema',
      'tables',
      "settings['routing']['allocation']['exclude']",
      'object',
    ],
    [
      'information_schema',
      'tables',
      "settings['routing']['allocation']['include']",
      'object',
    ],
    [
      'information_schema',
      'tables',
      "settings['routing']['allocation']['require']",
      'object',
    ],
    [
      'information_schema',
      'tables',
      "settings['routing']['allocation']['total_shards_per_node']",
      'integer',
    ],
    ['information_schema', 'tables', "settings['store']", 'object'],
    ['information_schema', 'tables', "settings['store']['type']", 'text'],
    ['information_schema', 'tables', "settings['translog']", 'object'],
    ['information_schema', 'tables', "settings['translog']['durability']", 'text'],
    [
      'information_schema',
      'tables',
      "settings['translog']['flush_threshold_size']",
      'bigint',
    ],
    [
      'information_schema',
      'tables',
      "settings['translog']['sync_interval']",
      'bigint',
    ],
    ['information_schema', 'tables', "settings['unassigned']", 'object'],
    [
      'information_schema',
      'tables',
      "settings['unassigned']['node_left']",
      'object',
    ],
    [
      'information_schema',
      'tables',
      "settings['unassigned']['node_left']['delayed_timeout']",
      'bigint',
    ],
    ['information_schema', 'tables', "settings['warmer']", 'object'],
    ['information_schema', 'tables', "settings['warmer']['enabled']", 'boolean'],
    ['information_schema', 'tables', "settings['write']", 'object'],
    [
      'information_schema',
      'tables',
      "settings['write']['wait_for_active_shards']",
      'text',
    ],
    ['information_schema', 'tables', 'table_catalog', 'text'],
    ['information_schema', 'tables', 'table_name', 'text'],
    ['information_schema', 'tables', 'table_schema', 'text'],
    ['information_schema', 'tables', 'table_type', 'text'],
    ['information_schema', 'tables', 'version', 'object'],
    ['information_schema', 'tables', "version['created']", 'text'],
    ['information_schema', 'tables', "version['upgraded']", 'text'],
    [
      'information_schema',
      'user_mapping_options',
      'authorization_identifier',
      'text',
    ],
    ['information_schema', 'user_mapping_options', 'foreign_server_catalog', 'text'],
    ['information_schema', 'user_mapping_options', 'foreign_server_name', 'text'],
    ['information_schema', 'user_mapping_options', 'option_name', 'text'],
    ['information_schema', 'user_mapping_options', 'option_value', 'text'],
    ['information_schema', 'user_mappings', 'authorization_identifier', 'text'],
    ['information_schema', 'user_mappings', 'foreign_server_catalog', 'text'],
    ['information_schema', 'user_mappings', 'foreign_server_name', 'text'],
    ['information_schema', 'views', 'check_option', 'text'],
    ['information_schema', 'views', 'is_updatable', 'boolean'],
    ['information_schema', 'views', 'owner', 'text'],
    ['information_schema', 'views', 'table_catalog', 'text'],
    ['information_schema', 'views', 'table_name', 'text'],
    ['information_schema', 'views', 'table_schema', 'text'],
    ['information_schema', 'views', 'view_definition', 'text'],
    ['new_schema', 'new_table', 'id', 'bigint'],
    ['pg_catalog', 'pg_am', 'amhandler', 'regproc'],
    ['pg_catalog', 'pg_am', 'amname', 'text'],
    ['pg_catalog', 'pg_am', 'amtype', 'byte'],
    ['pg_catalog', 'pg_am', 'oid', 'integer'],
    ['pg_catalog', 'pg_attrdef', 'adbin', 'text'],
    ['pg_catalog', 'pg_attrdef', 'adnum', 'integer'],
    ['pg_catalog', 'pg_attrdef', 'adrelid', 'regclass'],
    ['pg_catalog', 'pg_attrdef', 'adsrc', 'text'],
    ['pg_catalog', 'pg_attrdef', 'oid', 'integer'],
    ['pg_catalog', 'pg_attribute', 'attacl', 'text_array'],
    ['pg_catalog', 'pg_attribute', 'attalign', 'text'],
    ['pg_catalog', 'pg_attribute', 'attbyval', 'boolean'],
    ['pg_catalog', 'pg_attribute', 'attcacheoff', 'integer'],
    ['pg_catalog', 'pg_attribute', 'attcollation', 'integer'],
    ['pg_catalog', 'pg_attribute', 'attfdwoptions', 'text_array'],
    ['pg_catalog', 'pg_attribute', 'attgenerated', 'text'],
    ['pg_catalog', 'pg_attribute', 'atthasdef', 'boolean'],
    ['pg_catalog', 'pg_attribute', 'atthasmissing', 'boolean'],
    ['pg_catalog', 'pg_attribute', 'attidentity', 'text'],
    ['pg_catalog', 'pg_attribute', 'attinhcount', 'integer'],
    ['pg_catalog', 'pg_attribute', 'attisdropped', 'boolean'],
    ['pg_catalog', 'pg_attribute', 'attislocal', 'boolean'],
    ['pg_catalog', 'pg_attribute', 'attlen', 'smallint'],
    ['pg_catalog', 'pg_attribute', 'attmissingval', 'text_array'],
    ['pg_catalog', 'pg_attribute', 'attname', 'text'],
    ['pg_catalog', 'pg_attribute', 'attndims', 'integer'],
    ['pg_catalog', 'pg_attribute', 'attnotnull', 'boolean'],
    ['pg_catalog', 'pg_attribute', 'attnum', 'integer'],
    ['pg_catalog', 'pg_attribute', 'attoptions', 'text_array'],
    ['pg_catalog', 'pg_attribute', 'attrelid', 'regclass'],
    ['pg_catalog', 'pg_attribute', 'attstattarget', 'integer'],
    ['pg_catalog', 'pg_attribute', 'attstorage', 'text'],
    ['pg_catalog', 'pg_attribute', 'atttypid', 'integer'],
    ['pg_catalog', 'pg_attribute', 'atttypmod', 'integer'],
    ['pg_catalog', 'pg_class', 'oid', 'regclass'],
    ['pg_catalog', 'pg_class', 'relacl', 'text_array'],
    ['pg_catalog', 'pg_class', 'relallvisible', 'integer'],
    ['pg_catalog', 'pg_class', 'relam', 'integer'],
    ['pg_catalog', 'pg_class', 'relchecks', 'smallint'],
    ['pg_catalog', 'pg_class', 'relfilenode', 'integer'],
    ['pg_catalog', 'pg_class', 'relforcerowsecurity', 'boolean'],
    ['pg_catalog', 'pg_class', 'relfrozenxid', 'integer'],
    ['pg_catalog', 'pg_class', 'relhasindex', 'boolean'],
    ['pg_catalog', 'pg_class', 'relhasrules', 'boolean'],
    ['pg_catalog', 'pg_class', 'relhassubclass', 'boolean'],
    ['pg_catalog', 'pg_class', 'relhastriggers', 'boolean'],
    ['pg_catalog', 'pg_class', 'relispartition', 'boolean'],
    ['pg_catalog', 'pg_class', 'relispopulated', 'boolean'],
    ['pg_catalog', 'pg_class', 'relisshared', 'boolean'],
    ['pg_catalog', 'pg_class', 'relkind', 'text'],
    ['pg_catalog', 'pg_class', 'relminmxid', 'integer'],
    ['pg_catalog', 'pg_class', 'relname', 'text'],
    ['pg_catalog', 'pg_class', 'relnamespace', 'integer'],
    ['pg_catalog', 'pg_class', 'relnatts', 'smallint'],
    ['pg_catalog', 'pg_class', 'reloftype', 'integer'],
    ['pg_catalog', 'pg_class', 'reloptions', 'text_array'],
    ['pg_catalog', 'pg_class', 'relowner', 'integer'],
    ['pg_catalog', 'pg_class', 'relpages', 'integer'],
    ['pg_catalog', 'pg_class', 'relpartbound', 'text'],
    ['pg_catalog', 'pg_class', 'relpersistence', 'text'],
    ['pg_catalog', 'pg_class', 'relreplident', 'text'],
    ['pg_catalog', 'pg_class', 'relrewrite', 'integer'],
    ['pg_catalog', 'pg_class', 'relrowsecurity', 'boolean'],
    ['pg_catalog', 'pg_class', 'reltablespace', 'integer'],
    ['pg_catalog', 'pg_class', 'reltoastrelid', 'integer'],
    ['pg_catalog', 'pg_class', 'reltuples', 'real'],
    ['pg_catalog', 'pg_class', 'reltype', 'integer'],
    ['pg_catalog', 'pg_constraint', 'conbin', 'text'],
    ['pg_catalog', 'pg_constraint', 'condeferrable', 'boolean'],
    ['pg_catalog', 'pg_constraint', 'condeferred', 'boolean'],
    ['pg_catalog', 'pg_constraint', 'conexclop', 'integer_array'],
    ['pg_catalog', 'pg_constraint', 'confdeltype', 'text'],
    ['pg_catalog', 'pg_constraint', 'conffeqop', 'integer_array'],
    ['pg_catalog', 'pg_constraint', 'confkey', 'smallint_array'],
    ['pg_catalog', 'pg_constraint', 'confmatchtype', 'text'],
    ['pg_catalog', 'pg_constraint', 'confrelid', 'integer'],
    ['pg_catalog', 'pg_constraint', 'confupdtype', 'text'],
    ['pg_catalog', 'pg_constraint', 'conindid', 'integer'],
    ['pg_catalog', 'pg_constraint', 'coninhcount', 'integer'],
    ['pg_catalog', 'pg_constraint', 'conislocal', 'boolean'],
    ['pg_catalog', 'pg_constraint', 'conkey', 'smallint_array'],
    ['pg_catalog', 'pg_constraint', 'conname', 'text'],
    ['pg_catalog', 'pg_constraint', 'connamespace', 'integer'],
    ['pg_catalog', 'pg_constraint', 'connoinherit', 'boolean'],
    ['pg_catalog', 'pg_constraint', 'conparentid', 'integer'],
    ['pg_catalog', 'pg_constraint', 'conpfeqop', 'integer_array'],
    ['pg_catalog', 'pg_constraint', 'conppeqop', 'integer_array'],
    ['pg_catalog', 'pg_constraint', 'conrelid', 'integer'],
    ['pg_catalog', 'pg_constraint', 'contype', 'text'],
    ['pg_catalog', 'pg_constraint', 'contypid', 'integer'],
    ['pg_catalog', 'pg_constraint', 'convalidated', 'boolean'],
    ['pg_catalog', 'pg_constraint', 'oid', 'integer'],
    ['pg_catalog', 'pg_cursors', 'creation_time', 'timestamp with time zone'],
    ['pg_catalog', 'pg_cursors', 'is_binary', 'boolean'],
    ['pg_catalog', 'pg_cursors', 'is_holdable', 'boolean'],
    ['pg_catalog', 'pg_cursors', 'is_scrollable', 'boolean'],
    ['pg_catalog', 'pg_cursors', 'name', 'text'],
    ['pg_catalog', 'pg_cursors', 'statement', 'text'],
    ['pg_catalog', 'pg_database', 'datacl', 'text_array'],
    ['pg_catalog', 'pg_database', 'datallowconn', 'boolean'],
    ['pg_catalog', 'pg_database', 'datcollate', 'text'],
    ['pg_catalog', 'pg_database', 'datconnlimit', 'integer'],
    ['pg_catalog', 'pg_database', 'datctype', 'text'],
    ['pg_catalog', 'pg_database', 'datdba', 'integer'],
    ['pg_catalog', 'pg_database', 'datfrozenxid', 'integer'],
    ['pg_catalog', 'pg_database', 'datistemplate', 'boolean'],
    ['pg_catalog', 'pg_database', 'datlastsysoid', 'integer'],
    ['pg_catalog', 'pg_database', 'datminmxid', 'integer'],
    ['pg_catalog', 'pg_database', 'datname', 'text'],
    ['pg_catalog', 'pg_database', 'dattablespace', 'integer'],
    ['pg_catalog', 'pg_database', 'encoding', 'integer'],
    ['pg_catalog', 'pg_database', 'oid', 'integer'],
    ['pg_catalog', 'pg_depend', 'classid', 'integer'],
    ['pg_catalog', 'pg_depend', 'deptype', 'character'],
    ['pg_catalog', 'pg_depend', 'objid', 'integer'],
    ['pg_catalog', 'pg_depend', 'objsubid', 'integer'],
    ['pg_catalog', 'pg_depend', 'refclassid', 'integer'],
    ['pg_catalog', 'pg_depend', 'refobjid', 'integer'],
    ['pg_catalog', 'pg_depend', 'refobjsubid', 'integer'],
    ['pg_catalog', 'pg_description', 'classoid', 'integer'],
    ['pg_catalog', 'pg_description', 'description', 'text'],
    ['pg_catalog', 'pg_description', 'objoid', 'integer'],
    ['pg_catalog', 'pg_description', 'objsubid', 'integer'],
    ['pg_catalog', 'pg_enum', 'enumlabel', 'text'],
    ['pg_catalog', 'pg_enum', 'enumsortorder', 'real'],
    ['pg_catalog', 'pg_enum', 'enumtypid', 'integer'],
    ['pg_catalog', 'pg_enum', 'oid', 'integer'],
    ['pg_catalog', 'pg_event_trigger', 'evtenabled', 'character'],
    ['pg_catalog', 'pg_event_trigger', 'evtevent', 'text'],
    ['pg_catalog', 'pg_event_trigger', 'evtfoid', 'integer'],
    ['pg_catalog', 'pg_event_trigger', 'evtname', 'text'],
    ['pg_catalog', 'pg_event_trigger', 'evtowner', 'integer'],
    ['pg_catalog', 'pg_event_trigger', 'evttags', 'text_array'],
    ['pg_catalog', 'pg_event_trigger', 'oid', 'integer'],
    ['pg_catalog', 'pg_index', 'indcheckxmin', 'boolean'],
    ['pg_catalog', 'pg_index', 'indclass', 'integer_array'],
    ['pg_catalog', 'pg_index', 'indcollation', 'integer_array'],
    ['pg_catalog', 'pg_index', 'indexprs', 'text'],
    ['pg_catalog', 'pg_index', 'indexrelid', 'regclass'],
    ['pg_catalog', 'pg_index', 'indimmediate', 'boolean'],
    ['pg_catalog', 'pg_index', 'indisclustered', 'boolean'],
    ['pg_catalog', 'pg_index', 'indisexclusion', 'boolean'],
    ['pg_catalog', 'pg_index', 'indislive', 'boolean'],
    ['pg_catalog', 'pg_index', 'indisprimary', 'boolean'],
    ['pg_catalog', 'pg_index', 'indisready', 'boolean'],
    ['pg_catalog', 'pg_index', 'indisreplident', 'boolean'],
    ['pg_catalog', 'pg_index', 'indisunique', 'boolean'],
    ['pg_catalog', 'pg_index', 'indisvalid', 'boolean'],
    ['pg_catalog', 'pg_index', 'indkey', 'integer_array'],
    ['pg_catalog', 'pg_index', 'indnatts', 'smallint'],
    ['pg_catalog', 'pg_index', 'indnkeyatts', 'smallint'],
    ['pg_catalog', 'pg_index', 'indoption', 'smallint_array'],
    ['pg_catalog', 'pg_index', 'indpred', 'text'],
    ['pg_catalog', 'pg_index', 'indrelid', 'regclass'],
    ['pg_catalog', 'pg_indexes', 'indexdef', 'text'],
    ['pg_catalog', 'pg_indexes', 'indexname', 'text'],
    ['pg_catalog', 'pg_indexes', 'schemaname', 'text'],
    ['pg_catalog', 'pg_indexes', 'tablename', 'text'],
    ['pg_catalog', 'pg_indexes', 'tablespace', 'text'],
    ['pg_catalog', 'pg_locks', 'classid', 'integer'],
    ['pg_catalog', 'pg_locks', 'database', 'integer'],
    ['pg_catalog', 'pg_locks', 'fastpath', 'boolean'],
    ['pg_catalog', 'pg_locks', 'granted', 'boolean'],
    ['pg_catalog', 'pg_locks', 'locktype', 'text'],
    ['pg_catalog', 'pg_locks', 'mode', 'text'],
    ['pg_catalog', 'pg_locks', 'objid', 'text'],
    ['pg_catalog', 'pg_locks', 'objsubid', 'smallint'],
    ['pg_catalog', 'pg_locks', 'page', 'integer'],
    ['pg_catalog', 'pg_locks', 'pid', 'integer'],
    ['pg_catalog', 'pg_locks', 'relation', 'integer'],
    ['pg_catalog', 'pg_locks', 'transactionid', 'integer'],
    ['pg_catalog', 'pg_locks', 'tuple', 'smallint'],
    ['pg_catalog', 'pg_locks', 'virtualtransaction', 'text'],
    ['pg_catalog', 'pg_locks', 'virtualxid', 'text'],
    ['pg_catalog', 'pg_locks', 'waitstart', 'timestamp with time zone'],
    ['pg_catalog', 'pg_namespace', 'nspacl', 'text_array'],
    ['pg_catalog', 'pg_namespace', 'nspname', 'text'],
    ['pg_catalog', 'pg_namespace', 'nspowner', 'integer'],
    ['pg_catalog', 'pg_namespace', 'oid', 'integer'],
    ['pg_catalog', 'pg_proc', 'oid', 'integer'],
    ['pg_catalog', 'pg_proc', 'proacl', 'text_array'],
    ['pg_catalog', 'pg_proc', 'proallargtypes', 'integer_array'],
    ['pg_catalog', 'pg_proc', 'proargdefaults', 'text'],
    ['pg_catalog', 'pg_proc', 'proargmodes', 'text_array'],
    ['pg_catalog', 'pg_proc', 'proargnames', 'text_array'],
    ['pg_catalog', 'pg_proc', 'proargtypes', 'oidvector'],
    ['pg_catalog', 'pg_proc', 'probin', 'text'],
    ['pg_catalog', 'pg_proc', 'proconfig', 'text_array'],
    ['pg_catalog', 'pg_proc', 'procost', 'real'],
    ['pg_catalog', 'pg_proc', 'proisstrict', 'boolean'],
    ['pg_catalog', 'pg_proc', 'prokind', 'text'],
    ['pg_catalog', 'pg_proc', 'prolang', 'integer'],
    ['pg_catalog', 'pg_proc', 'proleakproof', 'boolean'],
    ['pg_catalog', 'pg_proc', 'proname', 'text'],
    ['pg_catalog', 'pg_proc', 'pronamespace', 'integer'],
    ['pg_catalog', 'pg_proc', 'pronargdefaults', 'smallint'],
    ['pg_catalog', 'pg_proc', 'pronargs', 'smallint'],
    ['pg_catalog', 'pg_proc', 'proowner', 'integer'],
    ['pg_catalog', 'pg_proc', 'proparallel', 'text'],
    ['pg_catalog', 'pg_proc', 'proretset', 'boolean'],
    ['pg_catalog', 'pg_proc', 'prorettype', 'integer'],
    ['pg_catalog', 'pg_proc', 'prorows', 'real'],
    ['pg_catalog', 'pg_proc', 'prosecdef', 'boolean'],
    ['pg_catalog', 'pg_proc', 'prosqlbody', 'text'],
    ['pg_catalog', 'pg_proc', 'prosrc', 'text'],
    ['pg_catalog', 'pg_proc', 'prosupport', 'regproc'],
    ['pg_catalog', 'pg_proc', 'protrftypes', 'integer_array'],
    ['pg_catalog', 'pg_proc', 'provariadic', 'integer'],
    ['pg_catalog', 'pg_proc', 'provolatile', 'text'],
    ['pg_catalog', 'pg_publication', 'oid', 'integer'],
    ['pg_catalog', 'pg_publication', 'puballtables', 'boolean'],
    ['pg_catalog', 'pg_publication', 'pubdelete', 'boolean'],
    ['pg_catalog', 'pg_publication', 'pubinsert', 'boolean'],
    ['pg_catalog', 'pg_publication', 'pubname', 'text'],
    ['pg_catalog', 'pg_publication', 'pubowner', 'integer'],
    ['pg_catalog', 'pg_publication', 'pubupdate', 'boolean'],
    ['pg_catalog', 'pg_publication_tables', 'pubname', 'text'],
    ['pg_catalog', 'pg_publication_tables', 'schemaname', 'text'],
    ['pg_catalog', 'pg_publication_tables', 'tablename', 'text'],
    ['pg_catalog', 'pg_range', 'rngcanonical', 'regproc'],
    ['pg_catalog', 'pg_range', 'rngcollation', 'integer'],
    ['pg_catalog', 'pg_range', 'rngmultitypid', 'integer'],
    ['pg_catalog', 'pg_range', 'rngsubdiff', 'regproc'],
    ['pg_catalog', 'pg_range', 'rngsubopc', 'integer'],
    ['pg_catalog', 'pg_range', 'rngsubtype', 'integer'],
    ['pg_catalog', 'pg_range', 'rngtypid', 'integer'],
    ['pg_catalog', 'pg_roles', 'oid', 'integer'],
    ['pg_catalog', 'pg_roles', 'rolbypassrls', 'boolean'],
    ['pg_catalog', 'pg_roles', 'rolcanlogin', 'boolean'],
    ['pg_catalog', 'pg_roles', 'rolconfig', 'text_array'],
    ['pg_catalog', 'pg_roles', 'rolconnlimit', 'integer'],
    ['pg_catalog', 'pg_roles', 'rolcreatedb', 'boolean'],
    ['pg_catalog', 'pg_roles', 'rolcreaterole', 'boolean'],
    ['pg_catalog', 'pg_roles', 'rolinherit', 'boolean'],
    ['pg_catalog', 'pg_roles', 'rolname', 'text'],
    ['pg_catalog', 'pg_roles', 'rolpassword', 'text'],
    ['pg_catalog', 'pg_roles', 'rolreplication', 'boolean'],
    ['pg_catalog', 'pg_roles', 'rolsuper', 'boolean'],
    ['pg_catalog', 'pg_roles', 'rolvaliduntil', 'timestamp with time zone'],
    ['pg_catalog', 'pg_settings', 'boot_val', 'text'],
    ['pg_catalog', 'pg_settings', 'category', 'text'],
    ['pg_catalog', 'pg_settings', 'context', 'text'],
    ['pg_catalog', 'pg_settings', 'enumvals', 'text_array'],
    ['pg_catalog', 'pg_settings', 'extra_desc', 'text'],
    ['pg_catalog', 'pg_settings', 'max_val', 'text'],
    ['pg_catalog', 'pg_settings', 'min_val', 'text'],
    ['pg_catalog', 'pg_settings', 'name', 'text'],
    ['pg_catalog', 'pg_settings', 'pending_restart', 'boolean'],
    ['pg_catalog', 'pg_settings', 'reset_val', 'text'],
    ['pg_catalog', 'pg_settings', 'setting', 'text'],
    ['pg_catalog', 'pg_settings', 'short_desc', 'text'],
    ['pg_catalog', 'pg_settings', 'source', 'text'],
    ['pg_catalog', 'pg_settings', 'sourcefile', 'text'],
    ['pg_catalog', 'pg_settings', 'sourceline', 'integer'],
    ['pg_catalog', 'pg_settings', 'unit', 'text'],
    ['pg_catalog', 'pg_settings', 'vartype', 'text'],
    ['pg_catalog', 'pg_shdescription', 'classoid', 'integer'],
    ['pg_catalog', 'pg_shdescription', 'description', 'text'],
    ['pg_catalog', 'pg_shdescription', 'objoid', 'integer'],
    ['pg_catalog', 'pg_stats', 'attname', 'text'],
    ['pg_catalog', 'pg_stats', 'avg_width', 'integer'],
    ['pg_catalog', 'pg_stats', 'correlation', 'real'],
    ['pg_catalog', 'pg_stats', 'elem_count_histogram', 'real_array'],
    ['pg_catalog', 'pg_stats', 'histogram_bounds', 'text_array'],
    ['pg_catalog', 'pg_stats', 'inherited', 'boolean'],
    ['pg_catalog', 'pg_stats', 'most_common_elem_freqs', 'real_array'],
    ['pg_catalog', 'pg_stats', 'most_common_elems', 'text_array'],
    ['pg_catalog', 'pg_stats', 'most_common_freqs', 'real_array'],
    ['pg_catalog', 'pg_stats', 'most_common_vals', 'text_array'],
    ['pg_catalog', 'pg_stats', 'n_distinct', 'real'],
    ['pg_catalog', 'pg_stats', 'null_frac', 'real'],
    ['pg_catalog', 'pg_stats', 'schemaname', 'text'],
    ['pg_catalog', 'pg_stats', 'tablename', 'text'],
    ['pg_catalog', 'pg_subscription', 'oid', 'integer'],
    ['pg_catalog', 'pg_subscription', 'subbinary', 'boolean'],
    ['pg_catalog', 'pg_subscription', 'subconninfo', 'text'],
    ['pg_catalog', 'pg_subscription', 'subdbid', 'integer'],
    ['pg_catalog', 'pg_subscription', 'subenabled', 'boolean'],
    ['pg_catalog', 'pg_subscription', 'subname', 'text'],
    ['pg_catalog', 'pg_subscription', 'subowner', 'text'],
    ['pg_catalog', 'pg_subscription', 'subpublications', 'text_array'],
    ['pg_catalog', 'pg_subscription', 'subslotname', 'text'],
    ['pg_catalog', 'pg_subscription', 'substream', 'boolean'],
    ['pg_catalog', 'pg_subscription', 'subsynccommit', 'text'],
    ['pg_catalog', 'pg_subscription_rel', 'srrelid', 'regclass'],
    ['pg_catalog', 'pg_subscription_rel', 'srsubid', 'integer'],
    ['pg_catalog', 'pg_subscription_rel', 'srsublsn', 'bigint'],
    ['pg_catalog', 'pg_subscription_rel', 'srsubstate', 'text'],
    ['pg_catalog', 'pg_subscription_rel', 'srsubstate_reason', 'text'],
    ['pg_catalog', 'pg_tables', 'hasindexes', 'boolean'],
    ['pg_catalog', 'pg_tables', 'hasrules', 'boolean'],
    ['pg_catalog', 'pg_tables', 'hastriggers', 'boolean'],
    ['pg_catalog', 'pg_tables', 'rowsecurity', 'boolean'],
    ['pg_catalog', 'pg_tables', 'schemaname', 'text'],
    ['pg_catalog', 'pg_tables', 'tablename', 'text'],
    ['pg_catalog', 'pg_tables', 'tableowner', 'text'],
    ['pg_catalog', 'pg_tables', 'tablespace', 'text'],
    ['pg_catalog', 'pg_tablespace', 'oid', 'integer'],
    ['pg_catalog', 'pg_tablespace', 'spcacl', 'text_array'],
    ['pg_catalog', 'pg_tablespace', 'spcname', 'text'],
    ['pg_catalog', 'pg_tablespace', 'spcoptions', 'text_array'],
    ['pg_catalog', 'pg_tablespace', 'spcowner', 'integer'],
    ['pg_catalog', 'pg_type', 'oid', 'integer'],
    ['pg_catalog', 'pg_type', 'typacl', 'text'],
    ['pg_catalog', 'pg_type', 'typalign', 'text'],
    ['pg_catalog', 'pg_type', 'typanalyze', 'regproc'],
    ['pg_catalog', 'pg_type', 'typarray', 'integer'],
    ['pg_catalog', 'pg_type', 'typbasetype', 'integer'],
    ['pg_catalog', 'pg_type', 'typbyval', 'boolean'],
    ['pg_catalog', 'pg_type', 'typcategory', 'text'],
    ['pg_catalog', 'pg_type', 'typcollation', 'integer'],
    ['pg_catalog', 'pg_type', 'typdefault', 'text'],
    ['pg_catalog', 'pg_type', 'typdefaultbin', 'text'],
    ['pg_catalog', 'pg_type', 'typdelim', 'text'],
    ['pg_catalog', 'pg_type', 'typelem', 'integer'],
    ['pg_catalog', 'pg_type', 'typinput', 'regproc'],
    ['pg_catalog', 'pg_type', 'typisdefined', 'boolean'],
    ['pg_catalog', 'pg_type', 'typlen', 'smallint'],
    ['pg_catalog', 'pg_type', 'typmodin', 'regproc'],
    ['pg_catalog', 'pg_type', 'typmodout', 'regproc'],
    ['pg_catalog', 'pg_type', 'typname', 'text'],
    ['pg_catalog', 'pg_type', 'typnamespace', 'integer'],
    ['pg_catalog', 'pg_type', 'typndims', 'integer'],
    ['pg_catalog', 'pg_type', 'typnotnull', 'boolean'],
    ['pg_catalog', 'pg_type', 'typoutput', 'regproc'],
    ['pg_catalog', 'pg_type', 'typowner', 'integer'],
    ['pg_catalog', 'pg_type', 'typreceive', 'regproc'],
    ['pg_catalog', 'pg_type', 'typrelid', 'integer'],
    ['pg_catalog', 'pg_type', 'typsend', 'regproc'],
    ['pg_catalog', 'pg_type', 'typstorage', 'text'],
    ['pg_catalog', 'pg_type', 'typsubscript', 'regproc'],
    ['pg_catalog', 'pg_type', 'typtype', 'text'],
    ['pg_catalog', 'pg_type', 'typtypmod', 'integer'],
    ['pg_catalog', 'pg_views', 'definition', 'text'],
    ['pg_catalog', 'pg_views', 'schemaname', 'text'],
    ['pg_catalog', 'pg_views', 'viewname', 'text'],
    ['pg_catalog', 'pg_views', 'viewowner', 'text'],
    ['sys', 'allocations', 'current_state', 'text'],
    ['sys', 'allocations', 'decisions', 'object_array'],
    ['sys', 'allocations', "decisions['explanations']", 'text_array_array'],
    ['sys', 'allocations', "decisions['node_id']", 'text_array'],
    ['sys', 'allocations', "decisions['node_name']", 'text_array'],
    ['sys', 'allocations', 'explanation', 'text'],
    ['sys', 'allocations', 'node_id', 'text'],
    ['sys', 'allocations', 'partition_ident', 'text'],
    ['sys', 'allocations', 'primary', 'boolean'],
    ['sys', 'allocations', 'shard_id', 'integer'],
    ['sys', 'allocations', 'table_name', 'text'],
    ['sys', 'allocations', 'table_schema', 'text'],
    ['sys', 'checks', 'description', 'text'],
    ['sys', 'checks', 'id', 'integer'],
    ['sys', 'checks', 'passed', 'boolean'],
    ['sys', 'checks', 'severity', 'integer'],
    ['sys', 'cluster', 'id', 'text'],
    ['sys', 'cluster', 'license', 'object'],
    ['sys', 'cluster', "license['expiry_date']", 'timestamp with time zone'],
    ['sys', 'cluster', "license['issued_to']", 'text'],
    ['sys', 'cluster', "license['max_nodes']", 'integer'],
    ['sys', 'cluster', 'master_node', 'text'],
    ['sys', 'cluster', 'name', 'text'],
    ['sys', 'cluster', 'settings', 'object'],
    ['sys', 'cluster', "settings['bulk']", 'object'],
    ['sys', 'cluster', "settings['bulk']['request_timeout']", 'text'],
    ['sys', 'cluster', "settings['cluster']", 'object'],
    ['sys', 'cluster', "settings['cluster']['graceful_stop']", 'object'],
    ['sys', 'cluster', "settings['cluster']['graceful_stop']['force']", 'boolean'],
    [
      'sys',
      'cluster',
      "settings['cluster']['graceful_stop']['min_availability']",
      'text',
    ],
    ['sys', 'cluster', "settings['cluster']['graceful_stop']['timeout']", 'text'],
    ['sys', 'cluster', "settings['cluster']['info']", 'object'],
    ['sys', 'cluster', "settings['cluster']['info']['update']", 'object'],
    ['sys', 'cluster', "settings['cluster']['info']['update']['interval']", 'text'],
    ['sys', 'cluster', "settings['cluster']['max_shards_per_node']", 'integer'],
    ['sys', 'cluster', "settings['cluster']['routing']", 'object'],
    ['sys', 'cluster', "settings['cluster']['routing']['allocation']", 'object'],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['allow_rebalance']",
      'text',
    ],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['balance']",
      'object',
    ],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['balance']['index']",
      'real',
    ],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['balance']['shard']",
      'real',
    ],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['balance']['threshold']",
      'real',
    ],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['cluster_concurrent_rebalance']",
      'integer',
    ],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['disk']",
      'object',
    ],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['disk']['threshold_enabled']",
      'boolean',
    ],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['disk']['watermark']",
      'object',
    ],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['disk']['watermark']['flood_stage']",
      'text',
    ],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['disk']['watermark']['high']",
      'text',
    ],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['disk']['watermark']['low']",
      'text',
    ],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['enable']",
      'text',
    ],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['exclude']",
      'object',
    ],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['exclude']['_host']",
      'text',
    ],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['exclude']['_id']",
      'text',
    ],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['exclude']['_ip']",
      'text',
    ],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['exclude']['_name']",
      'text',
    ],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['include']",
      'object',
    ],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['include']['_host']",
      'text',
    ],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['include']['_id']",
      'text',
    ],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['include']['_ip']",
      'text',
    ],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['include']['_name']",
      'text',
    ],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['node_concurrent_recoveries']",
      'integer',
    ],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['node_initial_primaries_recoveries']",
      'integer',
    ],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['require']",
      'object',
    ],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['require']['_host']",
      'text',
    ],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['require']['_id']",
      'text',
    ],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['require']['_ip']",
      'text',
    ],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['require']['_name']",
      'text',
    ],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['allocation']['total_shards_per_node']",
      'integer',
    ],
    ['sys', 'cluster', "settings['cluster']['routing']['rebalance']", 'object'],
    [
      'sys',
      'cluster',
      "settings['cluster']['routing']['rebalance']['enable']",
      'text',
    ],
    ['sys', 'cluster', "settings['fdw']", 'object'],
    ['sys', 'cluster', "settings['fdw']['allow_local']", 'boolean'],
    ['sys', 'cluster', "settings['gateway']", 'object'],
    ['sys', 'cluster', "settings['gateway']['expected_data_nodes']", 'integer'],
    ['sys', 'cluster', "settings['gateway']['expected_nodes']", 'integer'],
    ['sys', 'cluster', "settings['gateway']['recover_after_data_nodes']", 'integer'],
    ['sys', 'cluster', "settings['gateway']['recover_after_nodes']", 'integer'],
    ['sys', 'cluster', "settings['gateway']['recover_after_time']", 'text'],
    ['sys', 'cluster', "settings['indices']", 'object'],
    ['sys', 'cluster', "settings['indices']['breaker']", 'object'],
    ['sys', 'cluster', "settings['indices']['breaker']['query']", 'object'],
    ['sys', 'cluster', "settings['indices']['breaker']['query']['limit']", 'text'],
    ['sys', 'cluster', "settings['indices']['breaker']['request']", 'object'],
    ['sys', 'cluster', "settings['indices']['breaker']['request']['limit']", 'text'],
    ['sys', 'cluster', "settings['indices']['breaker']['total']", 'object'],
    ['sys', 'cluster', "settings['indices']['breaker']['total']['limit']", 'text'],
    ['sys', 'cluster', "settings['indices']['recovery']", 'object'],
    [
      'sys',
      'cluster',
      "settings['indices']['recovery']['internal_action_long_timeout']",
      'text',
    ],
    [
      'sys',
      'cluster',
      "settings['indices']['recovery']['internal_action_timeout']",
      'text',
    ],
    [
      'sys',
      'cluster',
      "settings['indices']['recovery']['max_bytes_per_sec']",
      'text',
    ],
    [
      'sys',
      'cluster',
      "settings['indices']['recovery']['recovery_activity_timeout']",
      'text',
    ],
    [
      'sys',
      'cluster',
      "settings['indices']['recovery']['retry_delay_network']",
      'text',
    ],
    [
      'sys',
      'cluster',
      "settings['indices']['recovery']['retry_delay_state_sync']",
      'text',
    ],
    ['sys', 'cluster', "settings['indices']['replication']", 'object'],
    [
      'sys',
      'cluster',
      "settings['indices']['replication']['retry_timeout']",
      'text',
    ],
    ['sys', 'cluster', "settings['logger']", 'object_array'],
    ['sys', 'cluster', "settings['logger']['level']", 'text_array'],
    ['sys', 'cluster', "settings['logger']['name']", 'text_array'],
    ['sys', 'cluster', "settings['memory']", 'object'],
    ['sys', 'cluster', "settings['memory']['allocation']", 'object'],
    ['sys', 'cluster', "settings['memory']['allocation']['type']", 'text'],
    ['sys', 'cluster', "settings['memory']['operation_limit']", 'integer'],
    ['sys', 'cluster', "settings['overload_protection']", 'object'],
    ['sys', 'cluster', "settings['overload_protection']['dml']", 'object'],
    [
      'sys',
      'cluster',
      "settings['overload_protection']['dml']['initial_concurrency']",
      'integer',
    ],
    [
      'sys',
      'cluster',
      "settings['overload_protection']['dml']['max_concurrency']",
      'integer',
    ],
    [
      'sys',
      'cluster',
      "settings['overload_protection']['dml']['min_concurrency']",
      'integer',
    ],
    [
      'sys',
      'cluster',
      "settings['overload_protection']['dml']['queue_size']",
      'integer',
    ],
    ['sys', 'cluster', "settings['replication']", 'object'],
    ['sys', 'cluster', "settings['replication']['logical']", 'object'],
    [
      'sys',
      'cluster',
      "settings['replication']['logical']['ops_batch_size']",
      'integer',
    ],
    [
      'sys',
      'cluster',
      "settings['replication']['logical']['reads_poll_duration']",
      'text',
    ],
    ['sys', 'cluster', "settings['replication']['logical']['recovery']", 'object'],
    [
      'sys',
      'cluster',
      "settings['replication']['logical']['recovery']['chunk_size']",
      'text',
    ],
    [
      'sys',
      'cluster',
      "settings['replication']['logical']['recovery']['max_concurrent_file_chunks']",
      'integer',
    ],
    ['sys', 'cluster', "settings['statement_timeout']", 'text'],
    ['sys', 'cluster', "settings['stats']", 'object'],
    ['sys', 'cluster', "settings['stats']['breaker']", 'object'],
    ['sys', 'cluster', "settings['stats']['breaker']['log']", 'object'],
    ['sys', 'cluster', "settings['stats']['breaker']['log']['jobs']", 'object'],
    [
      'sys',
      'cluster',
      "settings['stats']['breaker']['log']['jobs']['limit']",
      'text',
    ],
    [
      'sys',
      'cluster',
      "settings['stats']['breaker']['log']['operations']",
      'object',
    ],
    [
      'sys',
      'cluster',
      "settings['stats']['breaker']['log']['operations']['limit']",
      'text',
    ],
    ['sys', 'cluster', "settings['stats']['enabled']", 'boolean'],
    ['sys', 'cluster', "settings['stats']['jobs_log_expiration']", 'text'],
    ['sys', 'cluster', "settings['stats']['jobs_log_filter']", 'text'],
    ['sys', 'cluster', "settings['stats']['jobs_log_persistent_filter']", 'text'],
    ['sys', 'cluster', "settings['stats']['jobs_log_size']", 'integer'],
    ['sys', 'cluster', "settings['stats']['operations_log_expiration']", 'text'],
    ['sys', 'cluster', "settings['stats']['operations_log_size']", 'integer'],
    ['sys', 'cluster', "settings['stats']['service']", 'object'],
    ['sys', 'cluster', "settings['stats']['service']['interval']", 'text'],
    ['sys', 'cluster', "settings['stats']['service']['max_bytes_per_sec']", 'text'],
    ['sys', 'cluster', "settings['udc']", 'object'],
    ['sys', 'cluster', "settings['udc']['enabled']", 'boolean'],
    ['sys', 'cluster', "settings['udc']['initial_delay']", 'text'],
    ['sys', 'cluster', "settings['udc']['interval']", 'text'],
    ['sys', 'cluster', "settings['udc']['url']", 'text'],
    ['sys', 'health', 'health', 'text'],
    ['sys', 'health', 'missing_shards', 'bigint'],
    ['sys', 'health', 'partition_ident', 'text'],
    ['sys', 'health', 'severity', 'smallint'],
    ['sys', 'health', 'table_name', 'text'],
    ['sys', 'health', 'table_schema', 'text'],
    ['sys', 'health', 'underreplicated_shards', 'bigint'],
    ['sys', 'jobs', 'id', 'text'],
    ['sys', 'jobs', 'node', 'object'],
    ['sys', 'jobs', "node['id']", 'text'],
    ['sys', 'jobs', "node['name']", 'text'],
    ['sys', 'jobs', 'started', 'timestamp with time zone'],
    ['sys', 'jobs', 'stmt', 'text'],
    ['sys', 'jobs', 'username', 'text'],
    ['sys', 'jobs_log', 'classification', 'object'],
    ['sys', 'jobs_log', "classification['labels']", 'text_array'],
    ['sys', 'jobs_log', "classification['type']", 'text'],
    ['sys', 'jobs_log', 'ended', 'timestamp with time zone'],
    ['sys', 'jobs_log', 'error', 'text'],
    ['sys', 'jobs_log', 'id', 'text'],
    ['sys', 'jobs_log', 'node', 'object'],
    ['sys', 'jobs_log', "node['id']", 'text'],
    ['sys', 'jobs_log', "node['name']", 'text'],
    ['sys', 'jobs_log', 'started', 'timestamp with time zone'],
    ['sys', 'jobs_log', 'stmt', 'text'],
    ['sys', 'jobs_log', 'username', 'text'],
    ['sys', 'jobs_metrics', 'classification', 'object'],
    ['sys', 'jobs_metrics', "classification['labels']", 'text_array'],
    ['sys', 'jobs_metrics', "classification['type']", 'text'],
    ['sys', 'jobs_metrics', 'failed_count', 'bigint'],
    ['sys', 'jobs_metrics', 'max', 'bigint'],
    ['sys', 'jobs_metrics', 'mean', 'double precision'],
    ['sys', 'jobs_metrics', 'min', 'bigint'],
    ['sys', 'jobs_metrics', 'node', 'object'],
    ['sys', 'jobs_metrics', "node['id']", 'text'],
    ['sys', 'jobs_metrics', "node['name']", 'text'],
    ['sys', 'jobs_metrics', 'percentiles', 'object'],
    ['sys', 'jobs_metrics', "percentiles['25']", 'bigint'],
    ['sys', 'jobs_metrics', "percentiles['50']", 'bigint'],
    ['sys', 'jobs_metrics', "percentiles['75']", 'bigint'],
    ['sys', 'jobs_metrics', "percentiles['90']", 'bigint'],
    ['sys', 'jobs_metrics', "percentiles['95']", 'bigint'],
    ['sys', 'jobs_metrics', "percentiles['99']", 'bigint'],
    ['sys', 'jobs_metrics', 'stdev', 'double precision'],
    ['sys', 'jobs_metrics', 'sum_of_durations', 'bigint'],
    ['sys', 'jobs_metrics', 'total_count', 'bigint'],
    ['sys', 'node_checks', 'acknowledged', 'boolean'],
    ['sys', 'node_checks', 'description', 'text'],
    ['sys', 'node_checks', 'id', 'integer'],
    ['sys', 'node_checks', 'node_id', 'text'],
    ['sys', 'node_checks', 'passed', 'boolean'],
    ['sys', 'node_checks', 'severity', 'integer'],
    ['sys', 'nodes', 'attributes', 'object'],
    ['sys', 'nodes', 'cluster_state_version', 'bigint'],
    ['sys', 'nodes', 'connections', 'object'],
    ['sys', 'nodes', "connections['http']", 'object'],
    ['sys', 'nodes', "connections['http']['open']", 'bigint'],
    ['sys', 'nodes', "connections['http']['total']", 'bigint'],
    ['sys', 'nodes', "connections['psql']", 'object'],
    ['sys', 'nodes', "connections['psql']['open']", 'bigint'],
    ['sys', 'nodes', "connections['psql']['total']", 'bigint'],
    ['sys', 'nodes', "connections['transport']", 'object'],
    ['sys', 'nodes', "connections['transport']['open']", 'bigint'],
    ['sys', 'nodes', 'fs', 'object'],
    ['sys', 'nodes', "fs['data']", 'object_array'],
    ['sys', 'nodes', "fs['data']['dev']", 'text_array'],
    ['sys', 'nodes', "fs['data']['path']", 'text_array'],
    ['sys', 'nodes', "fs['disks']", 'object_array'],
    ['sys', 'nodes', "fs['disks']['available']", 'bigint_array'],
    ['sys', 'nodes', "fs['disks']['dev']", 'text_array'],
    ['sys', 'nodes', "fs['disks']['size']", 'bigint_array'],
    ['sys', 'nodes', "fs['disks']['used']", 'bigint_array'],
    ['sys', 'nodes', "fs['total']", 'object'],
    ['sys', 'nodes', "fs['total']['available']", 'bigint'],
    ['sys', 'nodes', "fs['total']['bytes_read']", 'bigint'],
    ['sys', 'nodes', "fs['total']['bytes_written']", 'bigint'],
    ['sys', 'nodes', "fs['total']['reads']", 'bigint'],
    ['sys', 'nodes', "fs['total']['size']", 'bigint'],
    ['sys', 'nodes', "fs['total']['used']", 'bigint'],
    ['sys', 'nodes', "fs['total']['writes']", 'bigint'],
    ['sys', 'nodes', 'heap', 'object'],
    ['sys', 'nodes', "heap['free']", 'bigint'],
    ['sys', 'nodes', "heap['max']", 'bigint'],
    ['sys', 'nodes', "heap['probe_timestamp']", 'timestamp with time zone'],
    ['sys', 'nodes', "heap['used']", 'bigint'],
    ['sys', 'nodes', 'hostname', 'text'],
    ['sys', 'nodes', 'id', 'text'],
    ['sys', 'nodes', 'load', 'object'],
    ['sys', 'nodes', "load['1']", 'double precision'],
    ['sys', 'nodes', "load['15']", 'double precision'],
    ['sys', 'nodes', "load['5']", 'double precision'],
    ['sys', 'nodes', "load['probe_timestamp']", 'timestamp with time zone'],
    ['sys', 'nodes', 'mem', 'object'],
    ['sys', 'nodes', "mem['free']", 'bigint'],
    ['sys', 'nodes', "mem['free_percent']", 'smallint'],
    ['sys', 'nodes', "mem['probe_timestamp']", 'timestamp with time zone'],
    ['sys', 'nodes', "mem['used']", 'bigint'],
    ['sys', 'nodes', "mem['used_percent']", 'smallint'],
    ['sys', 'nodes', 'name', 'text'],
    ['sys', 'nodes', 'network', 'object'],
    ['sys', 'nodes', "network['probe_timestamp']", 'timestamp with time zone'],
    ['sys', 'nodes', "network['tcp']", 'object'],
    ['sys', 'nodes', "network['tcp']['connections']", 'object'],
    ['sys', 'nodes', "network['tcp']['connections']['accepted']", 'bigint'],
    ['sys', 'nodes', "network['tcp']['connections']['curr_established']", 'bigint'],
    ['sys', 'nodes', "network['tcp']['connections']['dropped']", 'bigint'],
    ['sys', 'nodes', "network['tcp']['connections']['embryonic_dropped']", 'bigint'],
    ['sys', 'nodes', "network['tcp']['connections']['initiated']", 'bigint'],
    ['sys', 'nodes', "network['tcp']['packets']", 'object'],
    ['sys', 'nodes', "network['tcp']['packets']['errors_received']", 'bigint'],
    ['sys', 'nodes', "network['tcp']['packets']['received']", 'bigint'],
    ['sys', 'nodes', "network['tcp']['packets']['retransmitted']", 'bigint'],
    ['sys', 'nodes', "network['tcp']['packets']['rst_sent']", 'bigint'],
    ['sys', 'nodes', "network['tcp']['packets']['sent']", 'bigint'],
    ['sys', 'nodes', 'os', 'object'],
    ['sys', 'nodes', "os['cgroup']", 'object'],
    ['sys', 'nodes', "os['cgroup']['cpu']", 'object'],
    ['sys', 'nodes', "os['cgroup']['cpu']['cfs_period_micros']", 'bigint'],
    ['sys', 'nodes', "os['cgroup']['cpu']['cfs_quota_micros']", 'bigint'],
    ['sys', 'nodes', "os['cgroup']['cpu']['control_group']", 'text'],
    ['sys', 'nodes', "os['cgroup']['cpu']['num_elapsed_periods']", 'bigint'],
    ['sys', 'nodes', "os['cgroup']['cpu']['num_times_throttled']", 'bigint'],
    ['sys', 'nodes', "os['cgroup']['cpu']['time_throttled_nanos']", 'bigint'],
    ['sys', 'nodes', "os['cgroup']['cpuacct']", 'object'],
    ['sys', 'nodes', "os['cgroup']['cpuacct']['control_group']", 'text'],
    ['sys', 'nodes', "os['cgroup']['cpuacct']['usage_nanos']", 'bigint'],
    ['sys', 'nodes', "os['cgroup']['mem']", 'object'],
    ['sys', 'nodes', "os['cgroup']['mem']['control_group']", 'text'],
    ['sys', 'nodes', "os['cgroup']['mem']['limit_bytes']", 'text'],
    ['sys', 'nodes', "os['cgroup']['mem']['usage_bytes']", 'text'],
    ['sys', 'nodes', "os['cpu']", 'object'],
    ['sys', 'nodes', "os['cpu']['system']", 'smallint'],
    ['sys', 'nodes', "os['cpu']['used']", 'smallint'],
    ['sys', 'nodes', "os['cpu']['user']", 'smallint'],
    ['sys', 'nodes', "os['probe_timestamp']", 'timestamp with time zone'],
    ['sys', 'nodes', "os['timestamp']", 'timestamp with time zone'],
    ['sys', 'nodes', "os['uptime']", 'bigint'],
    ['sys', 'nodes', 'os_info', 'object'],
    ['sys', 'nodes', "os_info['arch']", 'text'],
    ['sys', 'nodes', "os_info['available_processors']", 'integer'],
    ['sys', 'nodes', "os_info['jvm']", 'object'],
    ['sys', 'nodes', "os_info['jvm']['version']", 'text'],
    ['sys', 'nodes', "os_info['jvm']['vm_name']", 'text'],
    ['sys', 'nodes', "os_info['jvm']['vm_vendor']", 'text'],
    ['sys', 'nodes', "os_info['jvm']['vm_version']", 'text'],
    ['sys', 'nodes', "os_info['name']", 'text'],
    ['sys', 'nodes', "os_info['version']", 'text'],
    ['sys', 'nodes', 'port', 'object'],
    ['sys', 'nodes', "port['http']", 'integer'],
    ['sys', 'nodes', "port['psql']", 'integer'],
    ['sys', 'nodes', "port['transport']", 'integer'],
    ['sys', 'nodes', 'process', 'object'],
    ['sys', 'nodes', "process['cpu']", 'object'],
    ['sys', 'nodes', "process['cpu']['percent']", 'smallint'],
    ['sys', 'nodes', "process['max_open_file_descriptors']", 'bigint'],
    ['sys', 'nodes', "process['open_file_descriptors']", 'bigint'],
    ['sys', 'nodes', "process['probe_timestamp']", 'timestamp with time zone'],
    ['sys', 'nodes', 'rest_url', 'text'],
    ['sys', 'nodes', 'thread_pools', 'object_array'],
    ['sys', 'nodes', "thread_pools['active']", 'integer_array'],
    ['sys', 'nodes', "thread_pools['completed']", 'bigint_array'],
    ['sys', 'nodes', "thread_pools['largest']", 'integer_array'],
    ['sys', 'nodes', "thread_pools['name']", 'text_array'],
    ['sys', 'nodes', "thread_pools['queue']", 'integer_array'],
    ['sys', 'nodes', "thread_pools['rejected']", 'bigint_array'],
    ['sys', 'nodes', "thread_pools['threads']", 'integer_array'],
    ['sys', 'nodes', 'version', 'object'],
    ['sys', 'nodes', "version['build_hash']", 'text'],
    ['sys', 'nodes', "version['build_snapshot']", 'boolean'],
    ['sys', 'nodes', "version['minimum_index_compatibility_version']", 'text'],
    ['sys', 'nodes', "version['minimum_wire_compatibility_version']", 'text'],
    ['sys', 'nodes', "version['number']", 'text'],
    ['sys', 'operations', 'id', 'text'],
    ['sys', 'operations', 'job_id', 'text'],
    ['sys', 'operations', 'name', 'text'],
    ['sys', 'operations', 'node', 'object'],
    ['sys', 'operations', "node['id']", 'text'],
    ['sys', 'operations', "node['name']", 'text'],
    ['sys', 'operations', 'started', 'timestamp with time zone'],
    ['sys', 'operations', 'used_bytes', 'bigint'],
    ['sys', 'operations_log', 'ended', 'timestamp with time zone'],
    ['sys', 'operations_log', 'error', 'text'],
    ['sys', 'operations_log', 'id', 'text'],
    ['sys', 'operations_log', 'job_id', 'text'],
    ['sys', 'operations_log', 'name', 'text'],
    ['sys', 'operations_log', 'started', 'timestamp with time zone'],
    ['sys', 'operations_log', 'used_bytes', 'bigint'],
    ['sys', 'privileges', 'class', 'text'],
    ['sys', 'privileges', 'grantee', 'text'],
    ['sys', 'privileges', 'grantor', 'text'],
    ['sys', 'privileges', 'ident', 'text'],
    ['sys', 'privileges', 'state', 'text'],
    ['sys', 'privileges', 'type', 'text'],
    ['sys', 'repositories', 'name', 'text'],
    ['sys', 'repositories', 'settings', 'object'],
    ['sys', 'repositories', 'type', 'text'],
    ['sys', 'roles', 'granted_roles', 'object_array'],
    ['sys', 'roles', "granted_roles['grantor']", 'text_array'],
    ['sys', 'roles', "granted_roles['role']", 'text_array'],
    ['sys', 'roles', 'name', 'text'],
    ['sys', 'segments', 'attributes', 'object'],
    ['sys', 'segments', 'committed', 'boolean'],
    ['sys', 'segments', 'compound', 'boolean'],
    ['sys', 'segments', 'deleted_docs', 'integer'],
    ['sys', 'segments', 'generation', 'bigint'],
    ['sys', 'segments', 'memory', 'bigint'],
    ['sys', 'segments', 'node', 'object'],
    ['sys', 'segments', "node['id']", 'text'],
    ['sys', 'segments', "node['name']", 'text'],
    ['sys', 'segments', 'num_docs', 'integer'],
    ['sys', 'segments', 'partition_ident', 'text'],
    ['sys', 'segments', 'primary', 'boolean'],
    ['sys', 'segments', 'search', 'boolean'],
    ['sys', 'segments', 'segment_name', 'text'],
    ['sys', 'segments', 'shard_id', 'integer'],
    ['sys', 'segments', 'size', 'bigint'],
    ['sys', 'segments', 'table_name', 'text'],
    ['sys', 'segments', 'table_schema', 'text'],
    ['sys', 'segments', 'version', 'text'],
    ['sys', 'shards', 'blob_path', 'text'],
    ['sys', 'shards', 'closed', 'boolean'],
    ['sys', 'shards', 'flush_stats', 'object'],
    ['sys', 'shards', "flush_stats['count']", 'bigint'],
    ['sys', 'shards', "flush_stats['periodic_count']", 'bigint'],
    ['sys', 'shards', "flush_stats['total_time_ns']", 'bigint'],
    ['sys', 'shards', 'id', 'integer'],
    ['sys', 'shards', 'min_lucene_version', 'text'],
    ['sys', 'shards', 'node', 'object'],
    ['sys', 'shards', "node['id']", 'text'],
    ['sys', 'shards', "node['name']", 'text'],
    ['sys', 'shards', 'num_docs', 'bigint'],
    ['sys', 'shards', 'orphan_partition', 'boolean'],
    ['sys', 'shards', 'partition_ident', 'text'],
    ['sys', 'shards', 'path', 'text'],
    ['sys', 'shards', 'primary', 'boolean'],
    ['sys', 'shards', 'recovery', 'object'],
    ['sys', 'shards', "recovery['files']", 'object'],
    ['sys', 'shards', "recovery['files']['percent']", 'real'],
    ['sys', 'shards', "recovery['files']['recovered']", 'integer'],
    ['sys', 'shards', "recovery['files']['reused']", 'integer'],
    ['sys', 'shards', "recovery['files']['used']", 'integer'],
    ['sys', 'shards', "recovery['size']", 'object'],
    ['sys', 'shards', "recovery['size']['percent']", 'real'],
    ['sys', 'shards', "recovery['size']['recovered']", 'bigint'],
    ['sys', 'shards', "recovery['size']['reused']", 'bigint'],
    ['sys', 'shards', "recovery['size']['used']", 'bigint'],
    ['sys', 'shards', "recovery['stage']", 'text'],
    ['sys', 'shards', "recovery['total_time']", 'bigint'],
    ['sys', 'shards', "recovery['type']", 'text'],
    ['sys', 'shards', 'relocating_node', 'text'],
    ['sys', 'shards', 'retention_leases', 'object'],
    ['sys', 'shards', "retention_leases['leases']", 'object_array'],
    ['sys', 'shards', "retention_leases['leases']['id']", 'text_array'],
    [
      'sys',
      'shards',
      "retention_leases['leases']['retaining_seq_no']",
      'bigint_array',
    ],
    ['sys', 'shards', "retention_leases['leases']['source']", 'text_array'],
    [
      'sys',
      'shards',
      "retention_leases['leases']['timestamp']",
      'timestamp with time zone_array',
    ],
    ['sys', 'shards', "retention_leases['primary_term']", 'bigint'],
    ['sys', 'shards', "retention_leases['version']", 'bigint'],
    ['sys', 'shards', 'routing_state', 'text'],
    ['sys', 'shards', 'schema_name', 'text'],
    ['sys', 'shards', 'seq_no_stats', 'object'],
    ['sys', 'shards', "seq_no_stats['global_checkpoint']", 'bigint'],
    ['sys', 'shards', "seq_no_stats['local_checkpoint']", 'bigint'],
    ['sys', 'shards', "seq_no_stats['max_seq_no']", 'bigint'],
    ['sys', 'shards', 'size', 'bigint'],
    ['sys', 'shards', 'state', 'text'],
    ['sys', 'shards', 'table_name', 'text'],
    ['sys', 'shards', 'translog_stats', 'object'],
    ['sys', 'shards', "translog_stats['number_of_operations']", 'integer'],
    ['sys', 'shards', "translog_stats['size']", 'bigint'],
    ['sys', 'shards', "translog_stats['uncommitted_operations']", 'integer'],
    ['sys', 'shards', "translog_stats['uncommitted_size']", 'bigint'],
    ['sys', 'snapshot_restore', 'id', 'text'],
    ['sys', 'snapshot_restore', 'name', 'text'],
    ['sys', 'snapshot_restore', 'repository', 'text'],
    ['sys', 'snapshot_restore', 'shards', 'object_array'],
    ['sys', 'snapshot_restore', "shards['partition_ident']", 'text_array'],
    ['sys', 'snapshot_restore', "shards['shard_id']", 'integer_array'],
    ['sys', 'snapshot_restore', "shards['state']", 'text_array'],
    ['sys', 'snapshot_restore', "shards['table_name']", 'text_array'],
    ['sys', 'snapshot_restore', "shards['table_schema']", 'text_array'],
    ['sys', 'snapshot_restore', 'state', 'text'],
    ['sys', 'snapshots', 'concrete_indices', 'text_array'],
    ['sys', 'snapshots', 'failures', 'text_array'],
    ['sys', 'snapshots', 'finished', 'timestamp with time zone'],
    ['sys', 'snapshots', 'name', 'text'],
    ['sys', 'snapshots', 'repository', 'text'],
    ['sys', 'snapshots', 'started', 'timestamp with time zone'],
    ['sys', 'snapshots', 'state', 'text'],
    ['sys', 'snapshots', 'table_partitions', 'object_array'],
    ['sys', 'snapshots', "table_partitions['table_name']", 'text_array'],
    ['sys', 'snapshots', "table_partitions['table_schema']", 'text_array'],
    ['sys', 'snapshots', "table_partitions['values']", 'text_array_array'],
    ['sys', 'snapshots', 'tables', 'text_array'],
    ['sys', 'snapshots', 'version', 'text'],
    ['sys', 'summits', 'classification', 'text'],
    ['sys', 'summits', 'coordinates', 'geo_point'],
    ['sys', 'summits', 'country', 'text'],
    ['sys', 'summits', 'first_ascent', 'integer'],
    ['sys', 'summits', 'height', 'integer'],
    ['sys', 'summits', 'mountain', 'text'],
    ['sys', 'summits', 'prominence', 'integer'],
    ['sys', 'summits', 'range', 'text'],
    ['sys', 'summits', 'region', 'text'],
    ['sys', 'users', 'granted_roles', 'object_array'],
    ['sys', 'users', "granted_roles['grantor']", 'text_array'],
    ['sys', 'users', "granted_roles['role']", 'text_array'],
    ['sys', 'users', 'jwt', 'object'],
    ['sys', 'users', "jwt['aud']", 'text'],
    ['sys', 'users', "jwt['iss']", 'text'],
    ['sys', 'users', "jwt['username']", 'text'],
    ['sys', 'users', 'name', 'text'],
    ['sys', 'users', 'password', 'text'],
    ['sys', 'users', 'superuser', 'boolean'],
  ],
  rowcount: 1041,
  duration: 2.215816,
};
