import { QueryResultSuccess } from 'types/query';

export const useSchemaTreeMock: QueryResultSuccess = {
  col_types: [],
  cols: [],
  rows: [
    ['gc', 'alembic_version', 'BASE TABLE', [['version_num']], ['text']],
    [
      'gc',
      'scheduled_jobs',
      'BASE TABLE',
      [
        ['id'],
        ['dc'],
        ['dc', 'modified'],
        ['dc', 'created'],
        ['name'],
        ['cron'],
        ['enabled'],
        ['sql'],
        ['sql_queries'],
        ['task'],
        ['task', 'type'],
        ['task', 'parameters'],
      ],
      [
        'text',
        'object',
        'bigint',
        'bigint',
        'text',
        'text',
        'boolean',
        'text',
        'text_array',
        'object',
        'text',
        'object',
      ],
    ],
    [
      'information_schema',
      'character_sets',
      'BASE TABLE',
      [
        ['character_repertoire'],
        ['character_set_catalog'],
        ['character_set_name'],
        ['character_set_schema'],
        ['default_collate_catalog'],
        ['default_collate_name'],
        ['default_collate_schema'],
        ['form_of_use'],
      ],
      ['text', 'text', 'text', 'text', 'text', 'text', 'text', 'text'],
    ],
    [
      'information_schema',
      'table_partitions',
      'BASE TABLE',
      [
        ['closed'],
        ['number_of_replicas'],
        ['number_of_shards'],
        ['partition_ident'],
        ['routing_hash_function'],
        ['settings'],
        ['settings', 'blocks'],
        ['settings', 'blocks', 'metadata'],
        ['settings', 'blocks', 'read'],
        ['settings', 'blocks', 'read_only'],
        ['settings', 'blocks', 'read_only_allow_delete'],
        ['settings', 'blocks', 'write'],
        ['settings', 'codec'],
        ['settings', 'mapping'],
        ['settings', 'mapping', 'total_fields'],
        ['settings', 'mapping', 'total_fields', 'limit'],
        ['settings', 'merge'],
        ['settings', 'merge', 'scheduler'],
        ['settings', 'merge', 'scheduler', 'max_merge_count'],
        ['settings', 'merge', 'scheduler', 'max_thread_count'],
        ['settings', 'routing'],
        ['settings', 'routing', 'allocation'],
        ['settings', 'routing', 'allocation', 'enable'],
        ['settings', 'routing', 'allocation', 'exclude'],
        ['settings', 'routing', 'allocation', 'include'],
        ['settings', 'routing', 'allocation', 'require'],
        ['settings', 'routing', 'allocation', 'total_shards_per_node'],
        ['settings', 'store'],
        ['settings', 'store', 'type'],
        ['settings', 'translog'],
        ['settings', 'translog', 'durability'],
        ['settings', 'translog', 'flush_threshold_size'],
        ['settings', 'translog', 'sync_interval'],
        ['settings', 'unassigned'],
        ['settings', 'unassigned', 'node_left'],
        ['settings', 'unassigned', 'node_left', 'delayed_timeout'],
        ['settings', 'write'],
        ['settings', 'write', 'wait_for_active_shards'],
        ['table_name'],
        ['table_schema'],
        ['values'],
        ['version'],
        ['version', 'created'],
        ['version', 'upgraded'],
      ],
      [
        'boolean',
        'text',
        'integer',
        'text',
        'text',
        'object',
        'object',
        'boolean',
        'boolean',
        'boolean',
        'boolean',
        'boolean',
        'text',
        'object',
        'object',
        'integer',
        'object',
        'object',
        'integer',
        'integer',
        'object',
        'object',
        'text',
        'object',
        'object',
        'object',
        'integer',
        'object',
        'text',
        'object',
        'text',
        'bigint',
        'bigint',
        'object',
        'object',
        'bigint',
        'object',
        'text',
        'text',
        'text',
        'object',
        'object',
        'text',
        'text',
      ],
    ],
    [
      'new_schema',
      'new_table',
      'BASE TABLE',
      [['campaign_id'], ['source']],
      ['text', 'text'],
    ],
    [
      'new_schema',
      'new_view',
      'VIEW',
      [['campaign_id'], ['source']],
      ['text', 'text'],
    ],
    [
      'pg_catalog',
      'pg_am',
      'BASE TABLE',
      [['amhandler'], ['amname'], ['amtype'], ['oid']],
      ['regproc', 'text', 'byte', 'integer'],
    ],
    [
      'pg_catalog',
      'pg_attrdef',
      'BASE TABLE',
      [['adbin'], ['adnum'], ['adrelid'], ['adsrc'], ['oid']],
      ['text', 'integer', 'regclass', 'text', 'integer'],
    ],
    [
      'sys',
      'allocations',
      'BASE TABLE',
      [
        ['current_state'],
        ['decisions'],
        ['decisions', 'explanations'],
        ['decisions', 'node_id'],
        ['decisions', 'node_name'],
        ['explanation'],
        ['node_id'],
        ['partition_ident'],
        ['primary'],
        ['shard_id'],
        ['table_name'],
        ['table_schema'],
      ],
      [
        'text',
        'object_array',
        'text_array_array',
        'text_array',
        'text_array',
        'text',
        'text',
        'text',
        'boolean',
        'integer',
        'text',
        'text',
      ],
    ],
    [
      'sys',
      'checks',
      'BASE TABLE',
      [['description'], ['id'], ['passed'], ['severity']],
      ['text', 'integer', 'boolean', 'integer'],
    ],
    [
      'sys',
      'users',
      'BASE TABLE',
      [
        ['granted_roles'],
        ['granted_roles', 'grantor'],
        ['granted_roles', 'role'],
        ['jwt'],
        ['jwt', 'aud'],
        ['jwt', 'iss'],
        ['jwt', 'username'],
        ['name'],
        ['password'],
        ['session_settings'],
        ['superuser'],
      ],
      [
        'object_array',
        'text_array',
        'text_array',
        'object',
        'text',
        'text',
        'text',
        'text',
        'text',
        'object',
        'boolean',
      ],
    ],
  ],
  rowcount: 1,
  duration: 123.45,
};
