import { QueryResultSuccess } from 'types/query';

export const useSchemaTreeMock: QueryResultSuccess = {
  col_types: [],
  cols: [],
  rows: [
    [
      'new_schema',
      'new_table',
      'campaign_id',
      'new_schema',
      'new_table',
      'campaign_id',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'new_schema',
      'new_table',
      'source',
      'new_schema',
      'new_table',
      'source',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'new_schema',
      'new_view',
      'campaign_id',
      'new_schema',
      'new_view',
      'campaign_id',
      'text',
      'VIEW',
      [],
    ],
    [
      'new_schema',
      'new_view',
      'source',
      'new_schema',
      'new_view',
      'source',
      'text',
      'VIEW',
      [],
    ],
    [
      'gc',
      'alembic_version',
      'version_num',
      'gc',
      'alembic_version',
      'version_num',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'gc',
      'jwt_refresh_token',
      'id',
      'gc',
      'jwt_refresh_token',
      'id',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'gc',
      'jwt_refresh_token',
      'refresh_token',
      'gc',
      'jwt_refresh_token',
      'refresh_token',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'gc',
      'scheduled_jobs',
      'id',
      'gc',
      'scheduled_jobs',
      'id',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'gc',
      'scheduled_jobs',
      'dc',
      'gc',
      'scheduled_jobs',
      'dc',
      'object',
      'BASE TABLE',
      [],
    ],
    [
      'gc',
      'scheduled_jobs_log',
      'job_id',
      'gc',
      'scheduled_jobs_log',
      'job_id',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'gc',
      'scheduled_jobs_log',
      'start',
      'gc',
      'scheduled_jobs_log',
      'start',
      'timestamp with time zone',
      'BASE TABLE',
      [],
    ],
    [
      'gc',
      'scheduled_jobs_state',
      'id',
      'gc',
      'scheduled_jobs_state',
      'id',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'gc',
      'scheduled_jobs_state',
      'next_run_time',
      'gc',
      'scheduled_jobs_state',
      'next_run_time',
      'double precision',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'character_sets',
      'character_repertoire',
      'information_schema',
      'character_sets',
      'character_repertoire',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'character_sets',
      'character_set_catalog',
      'information_schema',
      'character_sets',
      'character_set_catalog',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'columns',
      'character_maximum_length',
      'information_schema',
      'columns',
      'character_maximum_length',
      'integer',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'columns',
      'character_octet_length',
      'information_schema',
      'columns',
      'character_octet_length',
      'integer',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'foreign_server_options',
      'foreign_server_catalog',
      'information_schema',
      'foreign_server_options',
      'foreign_server_catalog',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'foreign_server_options',
      'foreign_server_name',
      'information_schema',
      'foreign_server_options',
      'foreign_server_name',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'foreign_servers',
      'authorization_identifier',
      'information_schema',
      'foreign_servers',
      'authorization_identifier',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'foreign_servers',
      'foreign_data_wrapper_catalog',
      'information_schema',
      'foreign_servers',
      'foreign_data_wrapper_catalog',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'foreign_table_options',
      'foreign_table_catalog',
      'information_schema',
      'foreign_table_options',
      'foreign_table_catalog',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'foreign_table_options',
      'foreign_table_name',
      'information_schema',
      'foreign_table_options',
      'foreign_table_name',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'foreign_tables',
      'foreign_server_catalog',
      'information_schema',
      'foreign_tables',
      'foreign_server_catalog',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'foreign_tables',
      'foreign_server_name',
      'information_schema',
      'foreign_tables',
      'foreign_server_name',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'key_column_usage',
      'column_name',
      'information_schema',
      'key_column_usage',
      'column_name',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'key_column_usage',
      'constraint_catalog',
      'information_schema',
      'key_column_usage',
      'constraint_catalog',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'referential_constraints',
      'constraint_catalog',
      'information_schema',
      'referential_constraints',
      'constraint_catalog',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'referential_constraints',
      'constraint_name',
      'information_schema',
      'referential_constraints',
      'constraint_name',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'routines',
      'data_type',
      'information_schema',
      'routines',
      'data_type',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'routines',
      'is_deterministic',
      'information_schema',
      'routines',
      'is_deterministic',
      'boolean',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'schemata',
      'schema_name',
      'information_schema',
      'schemata',
      'schema_name',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'sql_features',
      'comments',
      'information_schema',
      'sql_features',
      'comments',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'sql_features',
      'feature_id',
      'information_schema',
      'sql_features',
      'feature_id',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'table_constraints',
      'constraint_catalog',
      'information_schema',
      'table_constraints',
      'constraint_catalog',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'table_constraints',
      'constraint_name',
      'information_schema',
      'table_constraints',
      'constraint_name',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'table_partitions',
      'closed',
      'information_schema',
      'table_partitions',
      'closed',
      'boolean',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'table_partitions',
      'number_of_replicas',
      'information_schema',
      'table_partitions',
      'number_of_replicas',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'tables',
      'blobs_path',
      'information_schema',
      'tables',
      'blobs_path',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'tables',
      'closed',
      'information_schema',
      'tables',
      'closed',
      'boolean',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'user_mapping_options',
      'authorization_identifier',
      'information_schema',
      'user_mapping_options',
      'authorization_identifier',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'user_mapping_options',
      'foreign_server_catalog',
      'information_schema',
      'user_mapping_options',
      'foreign_server_catalog',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'user_mappings',
      'authorization_identifier',
      'information_schema',
      'user_mappings',
      'authorization_identifier',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'user_mappings',
      'foreign_server_catalog',
      'information_schema',
      'user_mappings',
      'foreign_server_catalog',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'views',
      'check_option',
      'information_schema',
      'views',
      'check_option',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'information_schema',
      'views',
      'is_updatable',
      'information_schema',
      'views',
      'is_updatable',
      'boolean',
      'BASE TABLE',
      [],
    ],
    [
      'pg_catalog',
      'pg_am',
      'amhandler',
      'pg_catalog',
      'pg_am',
      'amhandler',
      'regproc',
      'BASE TABLE',
      [],
    ],
    [
      'pg_catalog',
      'pg_am',
      'amname',
      'pg_catalog',
      'pg_am',
      'amname',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'pg_catalog',
      'pg_attrdef',
      'adbin',
      'pg_catalog',
      'pg_attrdef',
      'adbin',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'pg_catalog',
      'pg_attrdef',
      'adnum',
      'pg_catalog',
      'pg_attrdef',
      'adnum',
      'integer',
      'BASE TABLE',
      [],
    ],
    [
      'pg_catalog',
      'pg_attribute',
      'attacl',
      'pg_catalog',
      'pg_attribute',
      'attacl',
      'text_array',
      'BASE TABLE',
      [],
    ],
    [
      'pg_catalog',
      'pg_attribute',
      'attalign',
      'pg_catalog',
      'pg_attribute',
      'attalign',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'pg_catalog',
      'pg_class',
      'oid',
      'pg_catalog',
      'pg_class',
      'oid',
      'regclass',
      'BASE TABLE',
      [],
    ],
    [
      'pg_catalog',
      'pg_class',
      'relacl',
      'pg_catalog',
      'pg_class',
      'relacl',
      'text_array',
      'BASE TABLE',
      [],
    ],
    [
      'pg_catalog',
      'pg_constraint',
      'conbin',
      'pg_catalog',
      'pg_constraint',
      'conbin',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'pg_catalog',
      'pg_constraint',
      'condeferrable',
      'pg_catalog',
      'pg_constraint',
      'condeferrable',
      'boolean',
      'BASE TABLE',
      [],
    ],
    [
      'pg_catalog',
      'pg_cursors',
      'creation_time',
      'pg_catalog',
      'pg_cursors',
      'creation_time',
      'timestamp with time zone',
      'BASE TABLE',
      [],
    ],
    [
      'pg_catalog',
      'pg_cursors',
      'is_binary',
      'pg_catalog',
      'pg_cursors',
      'is_binary',
      'boolean',
      'BASE TABLE',
      [],
    ],
    [
      'pg_catalog',
      'pg_database',
      'datacl',
      'pg_catalog',
      'pg_database',
      'datacl',
      'text_array',
      'BASE TABLE',
      [],
    ],
    [
      'pg_catalog',
      'pg_database',
      'datallowconn',
      'pg_catalog',
      'pg_database',
      'datallowconn',
      'boolean',
      'BASE TABLE',
      [],
    ],
    [
      'pg_catalog',
      'pg_depend',
      'classid',
      'pg_catalog',
      'pg_depend',
      'classid',
      'integer',
      'BASE TABLE',
      [],
    ],
    [
      'pg_catalog',
      'pg_depend',
      'deptype',
      'pg_catalog',
      'pg_depend',
      'deptype',
      'character',
      'BASE TABLE',
      [],
    ],
    [
      'pg_catalog',
      'pg_description',
      'classoid',
      'pg_catalog',
      'pg_description',
      'classoid',
      'integer',
      'BASE TABLE',
      [],
    ],
    [
      'pg_catalog',
      'pg_description',
      'description',
      'pg_catalog',
      'pg_description',
      'description',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'pg_catalog',
      'pg_enum',
      'enumlabel',
      'pg_catalog',
      'pg_enum',
      'enumlabel',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'pg_catalog',
      'pg_enum',
      'enumsortorder',
      'pg_catalog',
      'pg_enum',
      'enumsortorder',
      'real',
      'BASE TABLE',
      [],
    ],
    [
      'sys',
      'allocations',
      'current_state',
      'sys',
      'allocations',
      'current_state',
      'text',
      'BASE TABLE',
      [],
    ],
    [
      'sys',
      'allocations',
      'decisions',
      'sys',
      'allocations',
      'decisions',
      'object_array',
      'BASE TABLE',
      [],
    ],
    [
      'sys',
      'checks',
      'description',
      'sys',
      'checks',
      'description',
      'text',
      'BASE TABLE',
      [],
    ],
    ['sys', 'checks', 'id', 'sys', 'checks', 'id', 'integer', 'BASE TABLE', []],
    ['sys', 'cluster', 'id', 'sys', 'cluster', 'id', 'text', 'BASE TABLE', []],
    [
      'sys',
      'cluster',
      'license',
      'sys',
      'cluster',
      'license',
      'object',
      'BASE TABLE',
      [],
    ],
    ['sys', 'health', 'health', 'sys', 'health', 'health', 'text', 'BASE TABLE', []],
    [
      'sys',
      'health',
      'missing_shards',
      'sys',
      'health',
      'missing_shards',
      'bigint',
      'BASE TABLE',
      [],
    ],
    ['sys', 'jobs', 'id', 'sys', 'jobs', 'id', 'text', 'BASE TABLE', []],
    ['sys', 'jobs', 'node', 'sys', 'jobs', 'node', 'object', 'BASE TABLE', []],
  ],
  rowcount: 1,
  duration: 123.45,
};
