import { QueryResultSuccess } from 'types/query';

export const useShardsMock: QueryResultSuccess = {
  col_types: [],
  cols: [],
  rows: [
    [
      'weather_data',
      'doc',
      'BFHeuv7bRGyPFSYNS2k8eQ',
      'STARTED',
      'STARTED',
      null,
      4,
      true,
      70000,
      17500,
      10450372,
    ],
    [
      'alembic_version',
      'gc',
      'BFHeuv7bRGyPFSYNS2k8eQ',
      'STARTED',
      'RELOCATING',
      null,
      1,
      true,
      1,
      1,
      20177,
    ],
    [
      'scheduled_jobs',
      'gc',
      'BFHeuv7bRGyPFSYNS2k8eQ',
      'STARTED',
      'RELOCATING',
      null,
      1,
      true,
      0,
      0,
      208,
    ],
  ],
  rowcount: 1,
  duration: 123.45,
};
