on:
  push:
    branches: master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: 'yarn'

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v2

      - name: Install dependencies
        if: steps.check.outputs.changed == 'true'
        run: yarn install

      - name: Build Lib
        if: steps.check.outputs.changed == 'true'
        run: yarn build-lib

      - name: Publish to npm
        if: steps.check.outputs.changed == 'true'
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create tag
        if: steps.check.outputs.changed == 'true'
        run: ./devtools/create_tag.sh