---
name: Publish to NPM

on:
  push:
    branches: master

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v2

      - name: Install dependencies
        if: steps.check.outputs.changed == 'true'
        run: yarn install

      - name: Build Lib
        if: steps.check.outputs.changed == 'true'
        run: yarn build-lib

      - name: Create tag
        if: steps.check.outputs.changed == 'true'
        run: echo y | ./devtools/create_tag.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm
        if: steps.check.outputs.changed == 'true'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
